CheckCollision
csit-sgu/mit-game-151 pull request #23
Opened 2023-04-15 18:29 UTC by Sayleyd

Проверка на "столкновение" двух объектов.

2023-04-15 18:56 UTC, nrydanov requested changes

2023-04-15 18:56 UTC, nrydanov commented on user.cpp
> +    Collision Collide{ false, { 0, 0 } };
Не стоит именовать переменные с заглавной. В подавляющем большинстве языков программирования соглашение о наименовании предполагает, что с заглавной пишутся имена классов, а не переменных. Вдвойне не хорошо это с учетом, что переменная является переменной локальной области видимости.

2023-04-15 18:56 UTC, nrydanov commented on user.cpp
> +    Vector2 q = {
Что у нас будет с приведением типов здесь?

2023-04-15 19:07 UTC, Sayleyd commented on user.cpp
> +    Collision Collide{ false, { 0, 0 } };
Исправлено.

2023-04-15 19:12 UTC, Sayleyd commented on user.cpp
> +    Vector2 q = {
В Vector2 position содержатся две переменные типа float (position.x и position.y), значит, если вызвать функцию abs, тип будет float.

2023-04-15 19:17 UTC, nrydanov commented on user.cpp
> +    Vector2 q = {
Github не очень удачно подсвечивает строчки, я про вектор d. 

Но сейчас глянул, там тоже всё ок с типами будет. Думал, что они int-овые. Сорян.

2023-04-15 19:17 UTC, nrydanov approved these changes
LGTM

2023-04-15 19:21 UTC, Sayleyd commented
Добавлена функция CheckCollision

2023-04-16 03:58 UTC, vasthecat requested changes

2023-04-16 03:58 UTC, vasthecat commented on user.cpp
> +    };
В задании по какой-то причине этого нет, поэтому напишу здесь.

Наши коллизии должны иметь знак. На основе этого знака определяется произошло ли столкновение слева/справа и сверху/снизу от объекта. В этой функции мы считаем столкновение с точки зрения obj1, поэтому overlap.x < 0 в том случае, если obj2 находится *левее* obj1. Аналогично для overlap.y.

Поэтому знаки чисел из d убирать не надо. Знаки компонент d копируются на знаки компонент q внутри следующего if.

2023-04-17 16:57 UTC, Sayleyd commented on user.cpp
> +    };
Не очень понятно задание. Например, у меня вот такой случай. obj1.position.x = 11, obj2.position.x = 3, ширина первого = 2, второго = 4. Тогда, если не учитывать знаки, в d первое значение будет равно 3- 11 = -8, а в q соответственно -8 - (2 + 4) / 2 = -8 - 3 = -11. Но объекты не пересекаются. Я исправил в своем решении знаки в значениях overlap.x и overlap.y в зависимости от расположения obj1 и obj2 соответственно. Так, если значение d.x > 0, то obj2 находится правее относительно obj1, тогда значение overlap.x будет положительным. Аналогично d.y.

2023-04-17 17:11 UTC, mchernigin approved these changes

2023-04-17 17:20 UTC, vasthecat commented on user.cpp
> +    };
> в q соответственно -8 - (2 + 4) / 2 = -8 - 3 = -11

Значение d берётся абсолютное, поэтому будет 8 - 3 = 5. В чём твой вопрос я не поняь.

2023-04-17 17:20 UTC, vasthecat approved these changes

2023-04-17 17:37 UTC, Sayleyd commented on user.cpp
> +    };
Я думал, что, может быть, не понимаю задание, поэтому написал пример. Но все хорошо.

2023-04-17 17:42 UTC, nrydanov requested changes
См. последний коммент к PR-у

И после того, как повесишь, выбирай Squash and Merge и нажимай зеленую кнопку счастья.

2023-04-17 17:46 UTC, nrydanov approved these changes

2023-04-17 17:48 UTC, merged