Добавлена реализация функции FixCollisions
csit-sgu/mit-game-151 pull request #25
Opened 2023-04-19 17:56 UTC by Mindero

2023-04-30 17:48 UTC, mchernigin requested changes

2023-04-30 17:48 UTC, mchernigin commented on user.cpp
> +                    SolveCollision(obj1, CheckCollision(obj1, obj2), 0.1);
Значение `dt` принимается 2 аргументом реализуемой функции, его и следует передать в `SolveCollision` 3 аргументом.

2023-04-30 17:48 UTC, mchernigin commented on user.cpp
> +        if (obj1.collider.enabled && obj1.collider.of_type(ColliderType::DYNAMIC))
Условие можно разбить на 2 строки, чтобы оно не превышало ограничение в 80 символов в одной строке:

```cpp
        if (obj1.collider.enabled &&
            obj1.collider.of_type(ColliderType::DYNAMIC))
```

2023-04-30 17:48 UTC, mchernigin commented on user.cpp
> +                    (obj2.collider.of_type(ColliderType::DYNAMIC) || obj2.collider.of_type(ColliderType::STATIC)))
Тут тоже можно поместиться в 80 символов:

```cpp
if (obj1 != obj2 && obj2.collider.enabled &&
    (obj2.collider.of_type(ColliderType::DYNAMIC) || 
     obj2.collider.of_type(ColliderType::STATIC)))
```

2023-05-02 20:09 UTC, Mindero commented on user.cpp
> +                    SolveCollision(obj1, CheckCollision(obj1, obj2), 0.1);
Исправлено

2023-05-02 21:05 UTC, nrydanov commented
Пожалуйста, делай "Resolve conversation" на тех изменениях, которые ты исправил. Так другим проверяющим будет проще ориентироваться, всё ли в новых коммитах исправлено или стоит обратить на них внимание.

Иногда "Resolve" делают, наоборот, ревьюеры, но в данном случае удобнее будет так...

И ещё, свяжи Pull Request с задачей (в разделе Development)

2023-05-05 19:49 UTC, nrydanov approved these changes
Кажется, всё должно работать корректно.

Но это мне так кажется...

2023-05-05 20:06 UTC, vasthecat approved these changes
LGTM

2023-05-09 10:45 UTC, merged