Добавлена гравитация объектам
csit-sgu/mit-game-151 pull request #27
Opened 2023-05-01 18:22 UTC by kirilliym

2023-05-05 20:13 UTC, vasthecat requested changes

2023-05-05 20:13 UTC, vasthecat commented on user.cpp
> +        obj.physics.acceleration.x += GRAVITY * dt * dt;
Гравитация - это ускорение по вертикальной оси, причём в отрицательную сторону.

2023-05-05 20:13 UTC, vasthecat commented on user.cpp
> +void ApplyGravity(Object& obj, float dt)
Зачем амперсанд к типу перемещён?

2023-05-05 20:17 UTC, nrydanov requested changes

2023-05-05 20:19 UTC, vasthecat commented
Ну и коммитить в форке в master можно, конечно, но всё же лучше создавать ветку даже в форке...

2023-05-07 17:22 UTC, kirilliym commented on user.cpp
> +        obj.physics.acceleration.x += GRAVITY * dt * dt;
Переделаю.

2023-05-07 17:23 UTC, kirilliym commented on user.cpp
> +void ApplyGravity(Object& obj, float dt)
Редактор автоматически сдвинул... переделаю.

2023-05-07 17:23 UTC, kirilliym commented on user.cpp
> +        if (obj.physics.speed.x > 200.0) obj.physics.speed.x = 200.0;
Верно, ошибся. Переделаю.

2023-05-07 17:24 UTC, kirilliym commented
Создан новый pull request с другой веткой.

2023-05-07 17:24 UTC, closed without merging