CheckPlayerDeath
csit-sgu/mit-game-151 pull request #29
Opened 2023-05-08 18:10 UTC by Lezgyan

2023-05-09 10:22 UTC, nrydanov requested changes

2023-05-09 10:22 UTC, nrydanov commented on user.cpp
> +	for (auto object : scene) {
Вот здесь кроется дьявол. Ключевое слово `auto` нужно использовать аккуратно и с умом, потому что компилятор не всегда выводит типы оптимальным образом.

Попробуй запустить этот пример и проверить, соответствует ли вывод программы твоим ожиданиям (если компилируешь через `g++`, то убедись, что есть флаг `-std=c++11`)

```
#include <iostream>
#include <vector>

class Obj {
public:
  int x;

  Obj() {
    this->x = 3;
    std::cout << "Object is created\n";
  }
};

int main() {
  std::vector<Obj> objs;
  for (int i = 0; i < 10; ++i) {
    objs.push_back(Obj());
  }

  for (auto obj : objs) {
    obj.x = 5;
  }

  for (auto obj : objs) {
    std::cout << obj.x << '\n';
  }
}
```

2023-05-09 10:22 UTC, nrydanov commented on user.cpp
> +	for (auto object : scene) {
Тем не менее, убирать `auto` не нужно, достаточно понять, в чем проблема и совсем немного изменить код, чтобы этот фрагмент работал как нужно.

2023-05-10 12:22 UTC, Lezgyan commented on user.cpp
> +	for (auto object : scene) {
Поправил, вроде теперь должно работать

2023-05-10 12:51 UTC, nrydanov approved these changes

2023-05-10 12:51 UTC, nrydanov commented on user.cpp
> +	for (auto& object : scene) {
Супер)

2023-05-10 12:53 UTC, mchernigin approved these changes

2023-05-10 13:28 UTC, merged