UpdateBullet
csit-sgu/mit-game-151 pull request #31
Opened 2023-05-11 16:43 UTC by citkniit

2023-05-11 17:32 UTC, nrydanov commented
Пожалуйста, свяжи Pull Request с задачей, которую ты выполняешь

2023-05-11 19:34 UTC, vasthecat requested changes

2023-05-11 19:34 UTC, vasthecat commented on user.cpp
> +    obj.bullet.position += obj.bullet.speed;
Любое изменение скорости должно учитывать время, прошедшее с прошлого кадра. Иначе скорости будут зависеть от скорости работы компьютера.

2023-05-12 16:56 UTC, nrydanov commented
Когда исправляешь недочет — запрашивай, пожалуйста, ревью заново и закрывай те дискуссии, недочеты по которым ты исправил.

2023-05-13 11:06 UTC, citkniit commented on user.cpp
> +    obj.bullet.position += obj.bullet.speed;
исправил

2023-05-14 08:02 UTC, nrydanov commented on user.cpp
> +        Destroy(ctx, obj);
Лично я считаю, что не очень крутая практика писать if без фигурных скобок, даже если команда if одна. Это ухудшает читаемость кода и предполагает необходимость эти скобки добавлять, если хотя бы ещё одна команда понадобится.

Если @vasthecat или @mchernigin со мной согласятся, то запрошу изменения.

2023-05-14 08:08 UTC, vasthecat requested changes

2023-05-14 08:08 UTC, vasthecat commented on user.cpp
> +        Destroy(ctx, obj);
В некоторых случаях можно оправдать отсутствие скобок, но тут, я думаю, стоит их добавить.

2023-05-14 08:09 UTC, nrydanov requested changes

2023-05-14 08:09 UTC, nrydanov commented on user.cpp
> +        Destroy(ctx, obj);
Ну, тогда кворум достигнут)

2023-05-14 08:14 UTC, nrydanov approved these changes
LGTM

2023-05-14 08:14 UTC, citkniit commented on user.cpp
> +        Destroy(ctx, obj);
Добавил

2023-05-14 08:32 UTC, vasthecat approved these changes
LGTM

2023-05-14 08:38 UTC, merged