Реализована функция PlayerControl
csit-sgu/mit-game-151 pull request #32
Opened 2023-05-14 23:36 UTC by Niashka4

2023-05-15 17:37 UTC, mchernigin requested changes

2023-05-15 17:37 UTC, mchernigin commented on user.cpp
> +        else if (IsKeyPressed(KEY_A)) player.position.x - (player.physics.speed.x * dt);
Выражение в теле конструкции `if` не имеет большого смысла: оно не изменяет значение `player.position.x`. Кроме того, в теле должен выставиться `player.player.direction` в `Direction::LEFT`

2023-05-15 17:37 UTC, mchernigin commented on user.cpp
> +        else if (IsKeyPressed(KEY_D)) player.position.x + (player.physics.speed.x * dt);
Аналогично строке выше

2023-05-15 17:37 UTC, mchernigin commented on user.cpp
> +        if (IsKeyDown(KEY_SPACE)) MakeJump(player, dt);
Это дело вкуса, но мне не нравятся конструкции `if` с телом в той же строке. Кажется, это негативно сказывается на читаемости кода. Это опционально, можешь оставить как есть.

2023-05-15 17:37 UTC, mchernigin commented on user.cpp
> +
В других местах между функциями ровно одна пустая строка, поэтому давай будем придерживаться того же и здесь

2023-05-18 09:58 UTC, mchernigin commented
Нажимай "Resolve conversation" под комментариями после исправлений

2023-05-18 15:06 UTC, mchernigin commented on user.cpp
> +        else if (IsKeyPressed(KEY_J))
Наличие `else` лишает возможности сочетать нажатие кнопок одновременно, например, движения вправо и прыжка. Нужно убрать `else` перед конструкциями `if`.

2023-05-18 15:17 UTC, mchernigin requested changes

2023-05-18 15:17 UTC, mchernigin commented on user.cpp
> +        else if (IsKeyPressed(KEY_J))
Есть подозрение, что проверять на нажатие клавиш следует с помощью функций `IsKeyDown`, а не `IsKeyPressed`.

2023-05-18 15:17 UTC, mchernigin commented on user.cpp
> +            player.position.x -= (player.physics.speed.x * dt);
Вместо `player.physics.speed.x` нужно использовать определённое число.

2023-05-18 18:54 UTC, Niashka4 commented on user.cpp
> +            player.position.x -= (player.physics.speed.x * dt);
А как понять какую константу взять для скорости игрока?

2023-05-23 20:08 UTC, mchernigin requested changes

2023-05-23 20:08 UTC, mchernigin commented on user.cpp
> +        if (IsKeyDown(KEY_J))
Он стреляет как сумасшедший. Кажется `IsKeyPressed` лучше подойдёт для стрельбы.

2023-05-25 14:40 UTC, mchernigin approved these changes
Достойно!

2023-05-26 20:46 UTC, nrydanov approved these changes

2023-05-27 15:40 UTC, nrydanov commented
@Niashka4 ты можешь смержить PR

2023-05-27 16:04 UTC, merged