Apply on spawn
csit-sgu/mit-game-151 pull request #33
Opened 2023-05-17 19:33 UTC by egnitii

2023-05-18 15:33 UTC, mchernigin requested changes

2023-05-18 15:33 UTC, mchernigin commented on user.cpp
> +        LoadSound(ctx, "shot1.mp3");
`LoadSound` возвращает объект типа `Sound`, который принимается функцией `PlaySound`.

Текущая версия не компилируется.

2023-05-18 15:33 UTC, mchernigin commented on user.cpp
> +     if (obj.bullet.enabled){
Пробел между `)` и `{`

2023-05-18 15:34 UTC, mchernigin commented
Ещё нужно добавить @vasthecat и @nrydanov в качестве Reviewers и себя в качестве Assignees.

2023-05-23 20:02 UTC, mchernigin requested changes

2023-05-23 20:02 UTC, mchernigin commented on user.cpp
> +        Sound shotSound = LoadSound(ctx, "shot1.mp3");
Нужно поправить путь: он должен вести к файлу из корня проекта `"Assets/..."`

2023-05-24 05:29 UTC, mchernigin approved these changes
Ок. Возможно, стоит удалить изначальный звук `shot.mp3`, но можно и оставить...

2023-05-26 20:47 UTC, nrydanov approved these changes

2023-05-27 13:35 UTC, merged