Реализована функция GameOverScreen Петром Стеклянниковым.
csit-sgu/mit-game-151 pull request #34
Opened 2023-05-18 20:23 UTC by Optoed

Реализовал GameOverScreen. Хотел ещё сделать так, чтобы текст появлялся не сразу, а плавно со временем, как и плавное затемнение экрана, но передумал (вдруг ещё всё сломается). 
Открыт к обратной связи!

2023-05-23 19:59 UTC, mchernigin requested changes

2023-05-23 19:59 UTC, mchernigin commented on user.cpp
> +    //RLAPI int MeasureText(const char *text, int fontSize);                              // Measure string width for default font
Комментарий с сигнатурой функции излишен. Его стоит удалить. То же самое встречается ниже

2023-05-23 19:59 UTC, mchernigin commented on user.cpp
Комментарии справа от кода нарушают ограничение в 80 символов в одной строке.
Я считаю многие комментарии излишними, если ты не согласен, можешь оставить, но расположить их в коде над теми блоками, к которым они относятся.

2023-05-23 19:59 UTC, mchernigin commented on user.cpp
> +    int posX = (ctx.screenWidth - textWidth) / 2;                                                         // Calculate the position to center the text on the screen
Этот код не компилируется.

2023-05-26 20:40 UTC, mchernigin requested changes
Этот код всё ещё не может быть скомпилирован: в `ctx` нет полей `screenWidth` и `screenHeight`

2023-05-29 08:01 UTC, vasthecat requested changes

2023-05-29 08:01 UTC, vasthecat commented on user.cpp
> +    int screenHeight = 1920, screeenWidth = 1080;
Это не скомпилируется так как в названии одной из переменных опечатка. К тому же непонятно откуда берутся значения для этих переменных и зачем они вообще нужны. В структуре Context есть поле screen_size.

2023-05-30 05:17 UTC, vasthecat approved these changes
В целом норм, но если всё ещё хочешь сделать плавное появление этого экрана, то можно это реализовать (немного костыльно, конечно).

Для этого можно добавить переменную `static unsigned char opacity = 0`. Так как функция вызывается каждый кадр, то можно прибавлять некоторое значение к переменной пока она меньше 255 (или меньше, если хочется полупрозрачный экран). Дальше можно заменить цвета `RED` и `BLACK` на `Color { 255, 0, 0, opacity }` и `Color { 0, 0, 0, opacity }`, чтобы их прозрачность постепенно изменялась. Главное, следить, чтобы значение не переполнилось при изменении.

Если не хочешь -- можешь мерджить.

2023-05-30 06:00 UTC, mchernigin approved these changes

2023-05-30 09:11 UTC, merged