Death sounds
csit-sgu/mit-game-151 pull request #38
Opened 2023-05-24 11:15 UTC by milanychh

2023-05-25 14:38 UTC, mchernigin requested changes
Нехорошо, что ты внесла эти изменения через сайт, а не терминал, как мы это показывали на лекции.

Чтобы всё было честно, предлагаю исправить небольшую ошибку в оформлении, и прислать это изменения НЕ через сайт.

2023-05-25 14:38 UTC, mchernigin commented on user.cpp
> +void ApplyOnDeath(Context &ctx, Object &obj) {
Фигурная скобка должна быть на новой строке, как во всех остальных функциях. Всё-таки хочется придерживаться единого стиля во всём проекте.

2023-05-26 20:50 UTC, nrydanov approved these changes
Всё хорошо с учетом исправления замечаний от @mchernigin

2023-05-27 15:39 UTC, nrydanov commented
@milanychh попроси у @mchernigin ревью заново туть
<img width="344" alt="image" src="https://github.com/csit-sgu/mit-game-151/assets/56316351/5e7f4ae8-9834-484c-b128-932f1007e20c">

2023-05-27 15:40 UTC, mchernigin approved these changes

2023-05-27 15:41 UTC, merged