Реализована функция DrawFinishScreen
csit-sgu/mit-game-151 pull request #42
Opened 2023-05-26 16:05 UTC by D0r0as

2023-05-26 19:39 UTC, mchernigin requested changes
Ок, но есть предложение добавить надпись о том, что можно начать игру сначала, нажав ENTER. Там как раз есть место в этом прямоугольнике под "WON!".

2023-05-26 19:49 UTC, mchernigin requested changes

2023-05-26 19:49 UTC, mchernigin commented on user.cpp
> +    const char* finish_text_message = "WON!";
Звёздочку обычно ставят у имени переменной, а не типа: 

```cpp
    const char *finish_text_message = "WON!";
```

2023-05-26 19:49 UTC, mchernigin commented on user.cpp
> +    DrawText(finish_text_message, point_x / 2 - inscription_size / 2, point_y / 3, 60, GREEN);
Тут превышено ограничение в 80 символов. Стоит перенести последние 3 аргумента на следующую строку.

2023-05-26 20:29 UTC, nrydanov commented on user.cpp
> +    const char* finish_text_message = "WON!";
Не соглашусь в данном случае. Считаю, что такого рода соглашение хоть и распространено, но не может быть однозначно или почти однозначно верным.

Если воспринимать * и & как часть типа (как это, например, вижу я), то гораздо логичнее ставить её слева, ближе к типу. Между тем считать эти символы частью типа кажется мне более логичным, поскольку объект, который передается в функцию, представляет из себя ссылку (или указатель) на элемент некоторого типа, что скорее описывает логику объекта и не имеет никакого отношения к его имени.

Конечно, с учетом того, что остальной проект использует соглашение писать * справа, то для единообразия, возможно, и лучше писать именно так, но в целом предпочтение какого-то одного из вариантов мне кажется спорным.

2023-05-27 13:36 UTC, nrydanov requested changes

2023-05-27 13:36 UTC, nrydanov commented on user.cpp
> +    const char *play_again = "clik ENTER to play again";
а чего `clik`-то... `click` же)

2023-05-27 15:54 UTC, D0r0as commented on user.cpp
> +    const char *play_again = "clik ENTER to play again";
А ой... Я из Англии...

2023-05-27 16:04 UTC, nrydanov approved these changes

2023-05-27 16:05 UTC, mchernigin requested changes
После исправлений нажимай "Resolve Conversation" под комментариями

2023-05-27 16:05 UTC, mchernigin commented on user.cpp
> +    point_y / 3, 60, GREEN);
При переносе стоит добавить табуляцию, это повысит читаемость кода. Будет понятнее, что это продолжение предыдущей строки.

2023-05-27 16:05 UTC, mchernigin commented on user.cpp
> +    point_y / 2, 30, BLUE);
И здесь тоже

2023-05-27 16:30 UTC, mchernigin requested changes

2023-05-27 16:30 UTC, mchernigin commented on user.cpp
> +	point_y / 3, 60, GREEN);
Под табуляцией я имел ввиду не таб как символ, а наличие дополнительного уровня табуляции:

```cpp
    DrawText(finish_text_message, point_x / 2 - inscription_size / 2,
        point_y / 3, 60, GREEN);
    DrawText(play_again, point_x / 2 - play_again_size / 2,
   	    point_y / 2, 30, BLUE);
```

2023-05-28 14:18 UTC, vasthecat approved these changes
Невероятно

2023-05-28 17:40 UTC, nrydanov commented
@D0r0as попроси у Миши заново ревью, поскольку его изменений не хватает для мержа PR-а

2023-05-28 18:27 UTC, mchernigin approved these changes
＼ʕ •ᴥ•ʔ／

2023-05-28 18:44 UTC, merged