Создан макет уровня
csit-sgu/mit-game-151 pull request #48
Opened 2023-05-28 15:54 UTC by D0r0as

2023-05-28 16:33 UTC, D0r0as commented
Так и должно все отображаться? Просто странно, что локально файл не так выглядит, в нем равные длины строк.

2023-05-28 17:20 UTC, nrydanov commented
Сомневаюсь, видно по числу строчек, что звездочек явно больше)

2023-05-28 17:23 UTC, nrydanov commented
А, не, это возможно приколы git diff-а просто.

Если твой уровень похож на это, то всё ок
<img width="835" alt="image" src="https://github.com/csit-sgu/mit-game-151/assets/56316351/63f21cda-bcdb-4b52-9fe2-121cf8c3f4ec">

2023-05-28 17:27 UTC, nrydanov requested changes

2023-05-28 17:27 UTC, nrydanov commented on Assets/game.lvl
> -================================
Нужно крабов добавить, а то как-то слишком легко...

2023-05-28 17:59 UTC, nrydanov commented
И ещё стоит добавить текстуры (см. описание к #22), иначе останутся отсутствующие текстуры.

2023-05-30 19:04 UTC, vasthecat approved these changes
norm

2023-05-31 17:09 UTC, mchernigin approved these changes
Концептуально

2023-06-01 18:42 UTC, nrydanov approved these changes

2023-06-01 18:44 UTC, merged