Добавлена реализация функции SolveCollisions
csit-sgu/mit-game-151 pull request #56
Opened 2023-05-31 17:47 UTC by Atsokolo

2023-06-01 18:43 UTC, nrydanov commented
Добавь @mchernigin, @vasthecat  и @nrydanov в качестве ревьюеров и свяжи PR с задачей

2023-06-01 19:57 UTC, mchernigin requested changes
Я подумал и понял, что я ничего не понял... оно не работает. Логические ошибки, которые сложно объяснить на полях этого пулл реквеста

2023-06-01 19:57 UTC, mchernigin commented on user.cpp
> +// FixCollisions.
Не нужно это менять

2023-06-01 19:57 UTC, mchernigin commented on user.cpp
> +        if(c.exists == true){
`c.exists` это уже `bool`. Не нужно сравнивать на равенство с `true`

2023-06-07 06:54 UTC, vasthecat approved these changes

2023-06-07 06:55 UTC, merged