Реализована функция MoveCameraTowards
csit-sgu/mit-game-151 pull request #57
Opened 2023-05-31 18:58 UTC by artermium

2023-05-31 19:09 UTC, mchernigin requested changes
В задании сказано "Необходимо, чтобы камера следовала за объектом obj с некоторым запозданием". На деле она просто прилипает к игроку...

2023-05-31 19:10 UTC, mchernigin commented
Необходимо добавить в Reviewers @vasthecat и @nrydanov, а также связать pull request с соответствующей issue

2023-05-31 20:02 UTC, artermium commented
Это зависит от скорости, можно её уменьшить и тогда всё будет плавнее

2023-06-01 07:36 UTC, mchernigin commented
Получается, что нужно уменьшить.

2023-06-05 16:25 UTC, artermium commented
так пойдёт?

2023-06-05 19:13 UTC, nrydanov commented
Закрытие PR-а не повлияет на наличие автомата, поэтому проверим на зачете.

2023-06-07 06:18 UTC, vasthecat approved these changes

2023-06-07 06:19 UTC, merged