Реализована функция DrawStatus
csit-sgu/mit-game-151 pull request #58
Opened 2023-06-01 18:40 UTC by YuraGolyshev

2023-06-01 19:18 UTC, mchernigin requested changes

2023-06-01 19:18 UTC, mchernigin commented on user.cpp
> +    itoa(int_sec, sec, 10);
Не нужно использовать `itoa`. В классе `std::string` есть прекрасная функция `std::to_string`.

2023-06-01 19:18 UTC, mchernigin commented on user.cpp
> +    if(int_min >= 10)
Нет пробела между `if` и скобкой. Повторяется в других местах

2023-06-01 19:18 UTC, mchernigin commented on user.cpp
> +    int min_posx = 755;
Эта переменная должна зависеть от размера окна. Если сейчас поменять его, то начнутся проблемы

2023-06-05 20:27 UTC, mchernigin approved these changes
Достаточно хорошо

2023-06-05 20:28 UTC, nrydanov commented
@YuraGolyshev можешь мерджить

2023-06-06 03:45 UTC, merged